language: python
python:
    - "2.7"
install:
    - pip install ansible
    - ansible-playbook -i test_host test.yml
script:
    - dpkg -s python-dev | grep Status
    - pip --version
    - easy_install --version
