---
- name: apt-get update
  apt: update_cache=yes

- name: Install packages from apt.
  apt: pkg={{ item }} state=latest
  with_items:
      - python-dev
      - python-pip

- name: Upgrade pip. Install setuptools.
  pip: name={{ item }} state=latest
  with_items:
      - pip
      - setuptools
